.TH microscopi 1 "April 2025" "0.10.0" "Microscopi manual"

.SH NAME
microscopi \- realtime measurement tool for USB microscopes

.SH SYNOPSIS
.B microscopi
.RI [ options ]

.SH DESCRIPTION
Microscopi is a realtime measurement tool designed for USB microscopes.

.SH OPTIONS
.TP
.B -d
Video device index.
.TP
.B -r
Resolution WIDTHxHEIGHT.
.TP
.B -n
Number of decimals.
